### ISSUE TITLE
Chapter view broken?

### ISSUE THREAD

**Issue by aka-raj** [bumpaneer/skin.unity#1]
Hello, I REALLY like this skin, one of the best. The chapters view doesn't look good though, at least on Xbian 15.2 RC, there are no thumbnail previews as provided in default Confluence, and the chapter titles are arranged vertically with large amount of white space between. Known issue?

**Comment by bumpaneer** [comment]
Hmm...looks fine on my side if I'm understanding where you are looking: http://i.imgur.com/cSaZtpH.png

If I've got it wrong, please let me know so I can get the issue corrected.

**Comment by aka-raj** [comment]
Yes it looks fine on your setup. Not on mine though. I'm on holiday this week but will try to get a screen-shot to you as soon as I can.

**Comment by aka-raj** [comment]
Screenshot. Not just this video file, seems to happen on all:
![screenshot034](https://cloud.githubusercontent.com/assets/1987162/10716855/6a028a18-7b3e-11e5-90f7-d7abc4445c33.jpg)

**Comment by bumpaneer** [comment]
From the Isengard alpha release notes (http://kodi.tv/kodi-15-0-isengard-alpha-2/) can you verify that the following is set?

 To enable visual chapters on slower devices, visit System -> Video -> File lists and select Extract chapter thumbnails. For speedy HTPCs, this setting is enabled by default.

**Comment by aka-raj** [comment]
Yes, that was it thanks. I was using an RPi2 for this skin and didn't notice the default setting for chapter thumbnails. Sorry. It never was a skin issue.
