### ISSUE TITLE
Seeking using forward and backwards is not working right

### ISSUE THREAD

**Issue by planet** [bumpaneer/skin.unity#10]
![image](https://user-images.githubusercontent.com/1265868/86199627-96b8c980-bb28-11ea-8d52-c30c2184b6f4.png)

Can't see the time to seek to because the text is overlapping the "chapter" text

**Comment by bumpaneer** [comment]
Fixed with https://github.com/bumpaneer/skin.unity/commit/80f16d1b4a54d31b1272fd3fe3db59aef3951b33

Thanks to @HamburgerJungeJr for the push in the right direction!
