### ISSUE TITLE
PVR has overlapping text in the channel description when you click up/down.

### ISSUE THREAD

**Issue by thecoldicelander** [bumpaneer/skin.unity#12]
![image](https://user-images.githubusercontent.com/62066726/93154433-95338200-f6d1-11ea-876a-efbf081742f2.png)

Looks like its showing the channel path from simple iptv,
I tried looking into this on my own but im afraid i don't know enough about kodi skinning to figure it out myself.

**Comment by bumpaneer** [comment]
Hopefully fixed with https://github.com/bumpaneer/skin.unity/commit/5d264d2c2ca32c76abf04c2aa4ffc40baf9ea7fd
