### ISSUE TITLE
Matrix 19. RED POSTERS 

### ISSUE THREAD

**Issue by adamforeman** [bumpaneer/skin.unity#14]
![IMG_20210227_121442548](https://user-images.githubusercontent.com/14033056/109386849-85ad9b80-78f5-11eb-8ab6-052bd14d9b1d.jpg)
There appears to be a bug whereby all the posters appear to have a red overlay on them. It also affects movie posters too. Strangely, some, not many, appear to be OK. 

See attached image. 

Matrix 19 Android. Stock, new fresh install.

Cheers for the awesome work

**Comment by bumpaneer** [comment]
Is this in an addon, or the default video library?

**Comment by sviet2k** [comment]
I have the same problem. 
It happens when the skin displays posters for kodi video library.

**Comment by adamforeman** [comment]
> Is this in an addon, or the default video library?

It appears to only affect TV Shows. The colour changes to what ever colour you choose using the "choose colour" option from the side menu. So picking red (default), all the TV posters have a red overlay on them. Change the colour to blue etc etc.

No additional addons installed

**Comment by bumpaneer** [comment]
Thanks for the details. Should be fixed with: c5f9bc3c19528ad2ff876bd9d1ff5a157211722b

Hopefully I'll get it pushed out to the repo in the next day or so.

**Comment by adamforeman** [comment]
> Thanks for the details. Should be fixed with: [c5f9bc3](https://github.com/bumpaneer/skin.unity/commit/c5f9bc3c19528ad2ff876bd9d1ff5a157211722b)
> 
> Hopefully I'll get it pushed out to the repo in the next day or so.

Thanks, I'll close the case once confirmed it's working. Cheers

**Comment by adamforeman** [comment]
This bug is fixed
