### ISSUE TITLE
Unable to fast forward/rewind using the remote on video timeline

### ISSUE THREAD

**Issue by adamforeman** [bumpaneer/skin.unity#19]
The issue is simple.

I'm using Matrix 19, Android (ATV), stock.

I'm unable to fast forward or rewind along the video timeline of the video you're currently watching.

Normally, I'd press the OK button which brings up the main gui of stop/start/fast forward, subtitles etc etc.

To move/fast forward through the video, I should be able to press up on the DPAD and then press left or right to move back and forth through the video eg fast forwarding through the starting and end credits.

Pressing up doesn't work currently.

Cheers!

Adam

**Comment by bumpaneer** [comment]
Should be fixed with da703e26a8cd68335c8164fc7fdf8d46a8e10fc0

**Comment by adamforeman** [comment]
> Should be fixed with [da703e2](https://github.com/bumpaneer/skin.unity/commit/da703e26a8cd68335c8164fc7fdf8d46a8e10fc0)

Will Close when confirmed.

Many thanks in advance

**Comment by adamforeman** [comment]
Confirmed fixed. However, please note that when the update gets installed, the whole main menu items gets reset, removing any custom menu items.

**Comment by bumpaneer** [comment]
Hopefully a 1 time thing. I've set Unity to not share it's menu with other skins using Skin Shortcuts to avoid compatibility errors. To quickly restore the previous layout, you should be able to use the "Restore menu items" option on the Customize Main Menu window. Then choose "Import from compatible skin" followed by "Shared menu" to restore your previous items.
