### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by scj643** [bumpaneer/skin.unity#2]
The font set has no Unicode support and isn't falling back to another font.

**Comment by scj643** [comment]
https://www.google.com/fonts/specimen/Cardo might help

**Comment by scj643** [comment]
One roadblock is getting a full font set would take up too much space which would cause low memory devices to not work.

**Comment by scj643** [comment]
We might want to use part of this http://www.google.com/get/noto/help/cjk/

**Comment by scj643** [comment]
The issue is we need to have the robots font combine with the arial font for unsupported glyphs

**Comment by bumpaneer** [comment]
Kodi will not fail over to another font if glyphs are not found.  The skin would have to be updated to add an additional font (such as Arial) as a user selectable option.  This would require realignment (or at least alignment checking) of all labels, buttons, lists, etc.  This is not a task I am current prepared to spend time on, but if you'd like to get it working and submit a pull request I'd be more than happy to take a look.

**Comment by scj643** [comment]
For the most part it's going to be media that will have the issue for example I have songs that have Japanese titles which by default don't show.
