### ISSUE TITLE
Cannot define custom background

### ISSUE THREAD

**Issue by flashkiller999** [bumpaneer/skin.unity#20]
**Hardware:**
Raspberry Pi 4 (4GB)
**Software:**
Libreelec 10
Kodi 19 (Matrix)
Plugin Version: 0.19.1

**Reproduction:**
Open Skin settings
Go to "Background"
Try to enable "Enable custom background"

**Expected behavior:**
Let the user browse for a custom image file to be used

**Exhibited behavior:**
Nothing (Meaning when trying to active the radio button, no error message is shown and no option to select an image, it is like I never tried to activate this option)

**Comment by bumpaneer** [comment]
Should be fixed with: b5e46bae72ee837c513e5eafecb4f0282349188e

**Comment by bumpaneer** [comment]
> **Hardware:**
> Raspberry Pi 4 (4GB)
> **Software:**
> Libreelec 10
> Kodi 19 (Matrix)
> Plugin Version: 0.19.1
> 
> **Reproduction:**
> Open Skin settings
> Go to "Background"
> Try to enable "Enable custom background"
> 
> **Expected behavior:**
> Let the user browse for a custom image file to be used
> 
> **Exhibited behavior:**
> Nothing (Meaning when trying to active the radio button, no error message is shown and no option to select an image, it is like I never tried to activate this option)

Are you able to confirm this is fixed?
