### ISSUE TITLE
4:3 support

### ISSUE THREAD

**Issue by scj643** [bumpaneer/skin.unity#3]
I love this skin and it works really well on iOS the only issue is the skin gets squashed so it can fit

**Comment by scj643** [comment]
Seems like the width of all elements would need to be multiplied by 3/4

**Comment by bumpaneer** [comment]
I have no test device to even begin to mock this up, so I'll leave it to someone else to submit a pull request with support for the desired resolution.

**Comment by scj643** [comment]
Wouldn't need a test device just have Kodi in a 4:3 screen resolution in windowed mode.

**Comment by scj643** [comment]
Also the only issue with the skin in 4:3 is some icons are squashed.
![image](https://cloud.githubusercontent.com/assets/5656510/10827883/98aa6d02-7e47-11e5-80a7-6badfd1bd350.png)

**Comment by bumpaneer** [comment]
As part of a larger effort, 4:3 support has been added:
https://github.com/bumpaneer/skin.unity/commit/5195e29adcbb6eaa998708a6aad977f02078c65f
