### ISSUE TITLE
LibreELEC repository

### ISSUE THREAD

**Issue by gilbertohasnofb** [bumpaneer/skin.unity#7]
I don't see your skin listed in my LibreELEC 9.0.0 installation on a Raspberry Pi 3 B+, but I do see it in my OSMC installation. Is there a reason this skin is not available by default for LibreELEC?

**Comment by bumpaneer** [comment]
Complete with the inclusion in the Leia repo: https://github.com/xbmc/repo-skins/commit/9b542ccd4712d008963cc0225ddb4691d9c6b570
