### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by Uranjitsu** [bumpaneer/skin.unity#8]
Hello,

first of all, thank you so much for your work.

A support for autocomplete would be very desirable.
https://kodi.tv/addon/plugins/autocompletion-virtual-keyboard

LG

**Comment by bumpaneer** [comment]
Until the autocomplete script works correctly on all Kodi versions, this will not be added:
https://forum.kodi.tv/showthread.php?tid=238712&pid=2858390#pid2858390
