### ISSUE TITLE
Cancel video

### ISSUE THREAD

**Issue by Uranjitsu** [bumpaneer/skin.unity#9]
FireTV:
When you watch a video and go back, the video continues to play in the background.

The selection menu is then no longer controllable. It would be nice if the video would end when you go back. In Skin.Pellucid this is possible. Maybe you can orientate yourself by it.

**Comment by bumpaneer** [comment]
There is no option in any skin that I am aware of that allows the video to stop on back. I tried Pellucid and the video continues to play when I back out, the same as Unity. See this forum post for more information: https://forum.kodi.tv/showthread.php?tid=324631

**Comment by bumpaneer** [comment]
Added in: https://github.com/bumpaneer/skin.unity/commit/f689a20ca17c8b6de532028c66405f9be131c446
